# permissions for end users to edit failuredomains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: egressipfailuredomain-editor-role
rules:
- apiGroups:
  - egressip.kaiserpfalz-edv.de
  resources:
  - failuredomains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - egressip.kaiserpfalz-edv.de
  resources:
    - egressipfailuredomains/status
  verbs:
  - get
