# permissions for end users to view failuredomains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: egressipfailuredomain-viewer-role
rules:
- apiGroups:
  - egressip.kaiserpfalz-edv.de
  resources:
  - failuredomains
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - egressip.kaiserpfalz-edv.de
  resources:
    - egressipfailuredomains/status
  verbs:
  - get
