
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
  - apiGroups:
      - egressip.kaiserpfalz-edv.de
    resources:
      - egressipfailuredomains
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - egressip.kaiserpfalz-edv.de
    resources:
      - egressipfailuredomains/status
    verbs:
      - create
      - delete
      - get
      - patch
      - update
  - apiGroups:
      - egressip.kaiserpfalz-edv.de
    resources:
      - egressips
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - egressip.kaiserpfalz-edv.de
    resources:
      - egressips/status
    verbs:
      - create
      - delete
      - get
      - patch
      - update
  - apiGroups:
      - network.openshift.io
    resources:
      - hostsubnets
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - network.openshift.io
    resources:
      - hostsubnets/status
    verbs:
      - create
      - delete
      - get
      - patch
      - update
