## Append samples you want in your CSV to this file as resources ##
resources:
  - egressip_v1alpha1_egressip.yaml
  - egressip_v1alpha1_egressipfailuredomain.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
